#include <stdlib.h>

#include "syscall.h"

const syscall_info SYSCALLS[] = {
    { "read", long_, 3, { uint_, string_, ulong_ } },
    { "write", long_, 3, { uint_, string_, ulong_ } },
    { "open", long_, 3, { string_, int_, uint_ } },
    { "close", long_, 1, { uint_ } },
    { "stat", long_, 2, { string_, pointer_ } },
    { "fstat", long_, 2, { uint_, pointer_ } },
    { "lstat", long_, 2, { string_, pointer_ } },
    { "poll", long_, 3, { pointer_, uint_, int_ } },
    { "lseek", long_, 3, { uint_, long_, uint_ } },
    { "mmap", long_, 6, { ulong_, ulong_, ulong_, ulong_, ulong_, ulong_ } },
    { "mprotect", long_, 3, { ulong_, ulong_, ulong_ } },
    { "munmap", long_, 2, { ulong_, ulong_ } },
    { "brk", long_, 1, { ulong_ } },
    { "rt_sigaction", long_, 4, { int_, pointer_, pointer_, ulong_ } },
    { "rt_sigprocmask", long_, 4, { int_, pointer_, pointer_, ulong_ } },
    { "rt_sigreturn", long_, 0, {  } },
    { "ioctl", long_, 3, { uint_, uint_, ulong_ } },
    { "pread64", long_, 4, { uint_, string_, ulong_, long_ } },
    { "pwrite64", long_, 4, { uint_, string_, ulong_, long_ } },
    { "readv", long_, 3, { ulong_, pointer_, ulong_ } },
    { "writev", long_, 3, { ulong_, pointer_, ulong_ } },
    { "access", long_, 2, { string_, int_ } },
    { "pipe", long_, 1, { pointer_ } },
    { "select", long_, 5, { int_, pointer_, pointer_, pointer_, pointer_ } },
    { "sched_yield", long_, 0, {  } },
    { "mremap", long_, 1, { ulong_ } },
    { "msync", long_, 3, { ulong_, ulong_, int_ } },
    { "mincore", long_, 3, { ulong_, ulong_, string_ } },
    { "madvise", long_, 3, { ulong_, ulong_, int_ } },
    { "shmget", long_, 3, { int_, ulong_, int_ } },
    { "shmat", long_, 3, { int_, string_, int_ } },
    { "shmctl", long_, 3, { int_, int_, pointer_ } },
    { "dup", long_, 1, { uint_ } },
    { "dup2", long_, 2, { uint_, uint_ } },
    { "pause", long_, 0, {  } },
    { "nanosleep", long_, 2, { pointer_, pointer_ } },
    { "getitimer", long_, 2, { int_, pointer_ } },
    { "alarm", long_, 1, { uint_ } },
    { "setitimer", long_, 3, { int_, pointer_, pointer_ } },
    { "getpid", long_, 0, {  } },
    { "sendfile", long_, 4, { int_, int_, pointer_, ulong_ } },
    { "socket", long_, 3, { int_, int_, int_ } },
    { "connect", long_, 3, { int_, pointer_, int_ } },
    { "accept", long_, 3, { int_, pointer_, pointer_ } },
    { "sendto", long_, 6, { int_, pointer_, ulong_, uint_, pointer_, int_ } },
    { "recvfrom", long_, 6, { int_, pointer_, ulong_, uint_, pointer_, pointer_ } },
    { "sendmsg", long_, 3, { int_, pointer_, uint_ } },
    { "recvmsg", long_, 3, { int_, pointer_, uint_ } },
    { "shutdown", long_, 2, { int_, int_ } },
    { "bind", long_, 3, { int_, pointer_, int_ } },
    { "listen", long_, 2, { int_, int_ } },
    { "getsockname", long_, 3, { int_, pointer_, pointer_ } },
    { "getpeername", long_, 3, { int_, pointer_, pointer_ } },
    { "socketpair", long_, 4, { int_, int_, int_, pointer_ } },
    { "setsockopt", long_, 5, { int_, int_, int_, string_, int_ } },
    { "getsockopt", long_, 5, { int_, int_, int_, string_, pointer_ } },
    { "clone", long_, 5, { ulong_, ulong_, pointer_, pointer_, int_ } },
    { "fork", long_, 0, {  } },
    { "vfork", long_, 0, {  } },
    { "execve", long_, 3, { string_, array_, array_ } },
    { "exit", long_, 1, { int_ } },
    { "wait4", long_, 4, { int_, pointer_, int_, pointer_ } },
    { "kill", long_, 2, { int_, int_ } },
    { "uname", long_, 1, { pointer_ } },
    { "semget", long_, 3, { int_, int_, int_ } },
    { "semop", long_, 3, { int_, pointer_, uint_ } },
    { "semctl", long_, 4, { int_, int_, int_, ulong_ } },
    { "shmdt", long_, 1, { string_ } },
    { "msgget", long_, 2, { int_, int_ } },
    { "msgsnd", long_, 4, { int_, pointer_, ulong_, int_ } },
    { "msgrcv", long_, 5, { int_, pointer_, ulong_, long_, int_ } },
    { "msgctl", long_, 3, { int_, int_, pointer_ } },
    { "fcntl", long_, 3, { uint_, uint_, ulong_ } },
    { "flock", long_, 2, { uint_, uint_ } },
    { "fsync", long_, 1, { uint_ } },
    { "fdatasync", long_, 1, { uint_ } },
    { "truncate", long_, 2, { string_, long_ } },
    { "ftruncate", long_, 2, { uint_, ulong_ } },
    { "getdents", long_, 3, { uint_, pointer_, uint_ } },
    { "getcwd", long_, 2, { string_, ulong_ } },
    { "chdir", long_, 1, { string_ } },
    { "fchdir", long_, 1, { uint_ } },
    { "rename", long_, 2, { string_, string_ } },
    { "mkdir", long_, 2, { string_, uint_ } },
    { "rmdir", long_, 1, { string_ } },
    { "creat", long_, 2, { string_, uint_ } },
    { "link", long_, 2, { string_, string_ } },
    { "unlink", long_, 1, { string_ } },
    { "symlink", long_, 2, { string_, string_ } },
    { "readlink", long_, 3, { string_, string_, int_ } },
    { "chmod", long_, 2, { string_, uint_ } },
    { "fchmod", long_, 2, { uint_, uint_ } },
    { "chown", long_, 3, { string_, uint_, uint_ } },
    { "fchown", long_, 3, { uint_, uint_, uint_ } },
    { "lchown", long_, 3, { string_, uint_, uint_ } },
    { "umask", long_, 1, { int_ } },
    { "gettimeofday", long_, 2, { pointer_, pointer_ } },
    { "getrlimit", long_, 2, { uint_, pointer_ } },
    { "getrusage", long_, 2, { int_, pointer_ } },
    { "sysinfo", long_, 1, { pointer_ } },
    { "times", long_, 1, { pointer_ } },
    { "ptrace", long_, 4, { long_, long_, ulong_, ulong_ } },
    { "getuid", long_, 0, {  } },
    { "syslog", long_, 3, { int_, string_, int_ } },
    { "getgid", long_, 0, {  } },
    { "setuid", long_, 1, { uint_ } },
    { "setgid", long_, 1, { uint_ } },
    { "geteuid", long_, 0, {  } },
    { "getegid", long_, 0, {  } },
    { "setpgid", long_, 2, { int_, int_ } },
    { "getppid", long_, 0, {  } },
    { "getpgrp", long_, 0, {  } },
    { "setsid", long_, 0, {  } },
    { "setreuid", long_, 2, { uint_, uint_ } },
    { "setregid", long_, 2, { uint_, uint_ } },
    { "getgroups", long_, 2, { int_, pointer_ } },
    { "setgroups", long_, 2, { int_, pointer_ } },
    { "setresuid", long_, 3, { uint_, uint_, uint_ } },
    { "getresuid", long_, 3, { pointer_, pointer_, pointer_ } },
    { "setresgid", long_, 3, { uint_, uint_, uint_ } },
    { "getresgid", long_, 3, { pointer_, pointer_, pointer_ } },
    { "getpgid", long_, 1, { int_ } },
    { "setfsuid", long_, 1, { uint_ } },
    { "setfsgid", long_, 1, { uint_ } },
    { "getsid", long_, 1, { int_ } },
    { "capget", long_, 2, { pointer_, pointer_ } },
    { "capset", long_, 2, { pointer_, pointer_ } },
    { "rt_sigpending", long_, 2, { pointer_, ulong_ } },
    { "rt_sigtimedwait", long_, 4, { pointer_, pointer_, pointer_, ulong_ } },
    { "rt_sigqueueinfo", long_, 3, { int_, int_, pointer_ } },
    { "rt_sigsuspend", long_, 2, { pointer_, ulong_ } },
    { "sigaltstack", long_, 2, { pointer_, pointer_ } },
    { "utime", long_, 2, { string_, pointer_ } },
    { "mknod", long_, 3, { string_, uint_, uint_ } },
    { "uselib", long_, 1, { string_ } },
    { "personality", long_, 1, { uint_ } },
    { "ustat", long_, 2, { uint_, pointer_ } },
    { "statfs", long_, 2, { string_, pointer_ } },
    { "fstatfs", long_, 2, { uint_, pointer_ } },
    { "sysfs", long_, 3, { int_, ulong_, ulong_ } },
    { "getpriority", long_, 2, { int_, int_ } },
    { "setpriority", long_, 3, { int_, int_, int_ } },
    { "sched_setparam", long_, 2, { int_, pointer_ } },
    { "sched_getparam", long_, 2, { int_, pointer_ } },
    { "sched_setscheduler", long_, 3, { int_, int_, pointer_ } },
    { "sched_getscheduler", long_, 1, { int_ } },
    { "sched_get_priority_max", long_, 1, { int_ } },
    { "sched_get_priority_min", long_, 1, { int_ } },
    { "sched_rr_get_interval", long_, 2, { int_, pointer_ } },
    { "mlock", long_, 2, { ulong_, ulong_ } },
    { "munlock", long_, 2, { ulong_, ulong_ } },
    { "mlockall", long_, 1, { int_ } },
    { "munlockall", long_, 0, {  } },
    { "vhangup", long_, 0, {  } },
    { "modify_ldt", long_, 3, { int_, pointer_, ulong_ } },
    { "pivot_root", long_, 2, { string_, string_ } },
    { "_sysctl", long_, 1, { pointer_ } },
    { "prctl", long_, 5, { int_, ulong_, ulong_, ulong_, ulong_ } },
    { "arch_prctl", long_, 3, { pointer_, int_, pointer_ } },
    { "adjtimex", long_, 1, { pointer_ } },
    { "setrlimit", long_, 2, { uint_, pointer_ } },
    { "chroot", long_, 1, { string_ } },
    { "sync", long_, 0, {  } },
    { "acct", long_, 1, { string_ } },
    { "settimeofday", long_, 2, { pointer_, pointer_ } },
    { "mount", long_, 5, { string_, string_, string_, ulong_, pointer_ } },
    { "umount2", long_, 2, { string_, int_ } },
    { "swapon", long_, 2, { string_, int_ } },
    { "swapoff", long_, 1, { string_ } },
    { "reboot", long_, 4, { int_, int_, uint_, pointer_ } },
    { "sethostname", long_, 2, { string_, int_ } },
    { "setdomainname", long_, 2, { string_, int_ } },
    { "iopl", long_, 1, { uint_ } },
    { "ioperm", long_, 3, { ulong_, ulong_, int_ } },
    { "create_module", long_, 0, {  } },
    { "init_module", long_, 3, { pointer_, ulong_, string_ } },
    { "delete_module", long_, 2, { string_, uint_ } },
    { "get_kernel_syms", long_, 0, {  } },
    { "query_module", long_, 0, {  } },
    { "quotactl", long_, 4, { uint_, string_, uint_, pointer_ } },
    { "nfsservctl", long_, 0, {  } },
    { "getpmsg", long_, 0, {  } },
    { "putpmsg", long_, 0, {  } },
    { "afs_syscall", long_, 0, {  } },
    { "tuxcall", long_, 0, {  } },
    { "security", long_, 0, {  } },
    { "gettid", long_, 0, {  } },
    { "readahead", long_, 3, { int_, long_, ulong_ } },
    { "setxattr", long_, 5, { string_, string_, pointer_, ulong_, int_ } },
    { "lsetxattr", long_, 5, { string_, string_, pointer_, ulong_, int_ } },
    { "fsetxattr", long_, 5, { int_, string_, pointer_, ulong_, int_ } },
    { "getxattr", long_, 4, { string_, string_, pointer_, ulong_ } },
    { "lgetxattr", long_, 4, { string_, string_, pointer_, ulong_ } },
    { "fgetxattr", long_, 4, { int_, string_, pointer_, ulong_ } },
    { "listxattr", long_, 3, { string_, string_, ulong_ } },
    { "llistxattr", long_, 3, { string_, string_, ulong_ } },
    { "flistxattr", long_, 3, { int_, string_, ulong_ } },
    { "removexattr", long_, 2, { string_, string_ } },
    { "lremovexattr", long_, 2, { string_, string_ } },
    { "fremovexattr", long_, 2, { int_, string_ } },
    { "tkill", long_, 2, { int_, int_ } },
    { "time", long_, 1, { pointer_ } },
    { "futex", long_, 6, { pointer_, int_, uint_, pointer_, pointer_, uint_ } },
    { "sched_setaffinity", long_, 3, { int_, uint_, pointer_ } },
    { "sched_getaffinity", long_, 3, { int_, uint_, pointer_ } },
    { "set_thread_area", long_, 1, { pointer_ } },
    { "io_setup", long_, 2, { uint_, pointer_ } },
    { "io_destroy", long_, 1, { ulong_ } },
    { "io_getevents", long_, 5, { ulong_, long_, long_, pointer_, pointer_ } },
    { "io_submit", long_, 3, { ulong_, long_, pointer_ } },
    { "io_cancel", long_, 3, { ulong_, pointer_, pointer_ } },
    { "get_thread_area", long_, 1, { pointer_ } },
    { "lookup_dcookie", long_, 3, { ulong_, string_, ulong_ } },
    { "epoll_create", long_, 1, { int_ } },
    { "epoll_ctl_old", long_, 0, {  } },
    { "epoll_wait_old", long_, 0, {  } },
    { "remap_file_pages", long_, 5, { ulong_, ulong_, ulong_, ulong_, ulong_ } },
    { "getdents64", long_, 3, { uint_, pointer_, uint_ } },
    { "set_tid_address", long_, 1, { pointer_ } },
    { "restart_syscall", long_, 0, {  } },
    { "semtimedop", long_, 4, { int_, pointer_, uint_, pointer_ } },
    { "fadvise64", long_, 4, { int_, long_, ulong_, int_ } },
    { "timer_create", long_, 3, { int_, pointer_, pointer_ } },
    { "timer_settime", long_, 4, { ulong_, int_, pointer_, pointer_ } },
    { "timer_gettime", long_, 2, { ulong_, pointer_ } },
    { "timer_getoverrun", long_, 1, { ulong_ } },
    { "timer_delete", long_, 1, { ulong_ } },
    { "clock_settime", long_, 2, { int_, pointer_ } },
    { "clock_gettime", long_, 2, { int_, pointer_ } },
    { "clock_getres", long_, 2, { int_, pointer_ } },
    { "clock_nanosleep", long_, 4, { int_, int_, pointer_, pointer_ } },
    { "exit_group", long_, 1, { int_ } },
    { "epoll_wait", long_, 4, { int_, pointer_, int_, int_ } },
    { "epoll_ctl", long_, 4, { int_, int_, int_, pointer_ } },
    { "tgkill", long_, 3, { int_, int_, int_ } },
    { "utimes", long_, 2, { string_, pointer_ } },
    { "vserver", long_, 0, {  } },
    { "mbind", long_, 6, { ulong_, ulong_, ulong_, pointer_, ulong_, uint_ } },
    { "set_mempolicy", long_, 3, { int_, pointer_, ulong_ } },
    { "get_mempolicy", long_, 5, { pointer_, pointer_, ulong_, ulong_, ulong_ } },
    { "mq_open", long_, 4, { string_, int_, uint_, pointer_ } },
    { "mq_unlink", long_, 1, { string_ } },
    { "mq_timedsend", long_, 5, { ulong_, string_, ulong_, uint_, pointer_ } },
    { "mq_timedreceive", long_, 5, { ulong_, string_, ulong_, pointer_, pointer_ } },
    { "mq_notify", long_, 2, { ulong_, pointer_ } },
    { "mq_getsetattr", long_, 3, { ulong_, pointer_, pointer_ } },
    { "kexec_load", long_, 4, { ulong_, ulong_, pointer_, ulong_ } },
    { "waitid", long_, 5, { int_, int_, pointer_, int_, pointer_ } },
    { "add_key", long_, 5, { string_, string_, pointer_, ulong_, int_ } },
    { "request_key", long_, 4, { string_, string_, string_, int_ } },
    { "keyctl", long_, 5, { int_, ulong_, ulong_, ulong_, ulong_ } },
    { "ioprio_set", long_, 3, { int_, int_, int_ } },
    { "ioprio_get", long_, 2, { int_, int_ } },
    { "inotify_init", long_, 0, {  } },
    { "inotify_add_watch", long_, 3, { int_, string_, uint_ } },
    { "inotify_rm_watch", long_, 2, { int_, int_ } },
    { "migrate_pages", long_, 4, { int_, ulong_, pointer_, pointer_ } },
    { "openat", long_, 4, { int_, string_, int_, uint_ } },
    { "mkdirat", long_, 3, { int_, string_, uint_ } },
    { "mknodat", long_, 4, { int_, string_, uint_, uint_ } },
    { "fchownat", long_, 5, { int_, string_, uint_, uint_, int_ } },
    { "futimesat", long_, 3, { int_, string_, pointer_ } },
    { "newfstatat", long_, 4, { int_, string_, pointer_, int_ } },
    { "unlinkat", long_, 3, { int_, string_, int_ } },
    { "renameat", long_, 4, { int_, string_, int_, string_ } },
    { "linkat", long_, 5, { int_, string_, int_, string_, int_ } },
    { "symlinkat", long_, 3, { string_, int_, string_ } },
    { "readlinkat", long_, 4, { int_, string_, string_, int_ } },
    { "fchmodat", long_, 3, { int_, string_, uint_ } },
    { "faccessat", long_, 3, { int_, string_, int_ } },
    { "pselect6", long_, 6, { int_, pointer_, pointer_, pointer_, pointer_, pointer_ } },
    { "ppoll", long_, 5, { pointer_, uint_, pointer_, pointer_, ulong_ } },
    { "unshare", long_, 1, { ulong_ } },
    { "set_robust_list", long_, 2, { pointer_, ulong_ } },
    { "get_robust_list", long_, 3, { int_, pointer_, pointer_ } },
    { "splice", long_, 6, { int_, pointer_, int_, pointer_, ulong_, uint_ } },
    { "tee", long_, 4, { int_, int_, ulong_, uint_ } },
    { "sync_file_range", long_, 4, { int_, long_, long_, uint_ } },
    { "vmsplice", long_, 4, { int_, pointer_, ulong_, uint_ } },
    { "move_pages", long_, 6, { int_, ulong_, pointer_, pointer_, pointer_, int_ } },
    { "utimensat", long_, 4, { int_, string_, pointer_, int_ } },
    { "epoll_pwait", long_, 6, { int_, pointer_, int_, int_, pointer_, ulong_ } },
    { "signalfd", long_, 3, { int_, pointer_, ulong_ } },
    { "timerfd_create", long_, 2, { int_, int_ } },
    { "eventfd", long_, 1, { uint_ } },
    { "fallocate", long_, 4, { int_, int_, long_, long_ } },
    { "timerfd_settime", long_, 4, { int_, int_, pointer_, pointer_ } },
    { "timerfd_gettime", long_, 2, { int_, pointer_ } },
    { "accept4", long_, 4, { int_, pointer_, pointer_, int_ } },
    { "signalfd4", long_, 4, { int_, pointer_, ulong_, int_ } },
    { "eventfd2", long_, 2, { uint_, int_ } },
    { "epoll_create1", long_, 1, { int_ } },
    { "dup3", long_, 3, { uint_, uint_, int_ } },
    { "pipe2", long_, 2, { pointer_, int_ } },
    { "inotify_init1", long_, 1, { int_ } },
    { "preadv", long_, 5, { ulong_, pointer_, ulong_, ulong_, ulong_ } },
    { "pwritev", long_, 5, { ulong_, pointer_, ulong_, ulong_, ulong_ } },
    { "rt_tgsigqueueinfo", long_, 4, { int_, int_, int_, pointer_ } },
    { "perf_event_open", long_, 5, { pointer_, int_, int_, int_, ulong_ } },
    { "recvmmsg", long_, 5, { int_, pointer_, uint_, uint_, pointer_ } },
    { "fanotify_init", long_, 2, { uint_, uint_ } },
    { "fanotify_mark", long_, 5, { int_, uint_, ulong_, int_, string_ } },
    { "prlimit64", long_, 4, { int_, uint_, pointer_, pointer_ } },
    { "name_to_handle_at", long_, 5, { int_, string_, pointer_, pointer_, int_ } },
    { "open_by_handle_at", long_, 3, { int_, pointer_, int_ } },
    { "clock_adjtime", long_, 2, { int_, pointer_ } },
    { "syncfs", long_, 1, { int_ } },
    { "sendmmsg", long_, 4, { int_, pointer_, uint_, uint_ } },
    { "setns", long_, 2, { int_, int_ } },
    { "getcpu", long_, 3, { pointer_, pointer_, pointer_ } },
    { "process_vm_readv", long_, 6, { int_, pointer_, ulong_, pointer_, ulong_, ulong_ } },
    { "process_vm_writev", long_, 6, { int_, pointer_, ulong_, pointer_, ulong_, ulong_ } },
    { "kcmp", long_, 5, { int_, int_, int_, ulong_, ulong_ } },
    { "finit_module", long_, 3, { int_, string_, int_ } },
};

const syscall_info *get_syscall_info(long syscall_id)
{
    const syscall_info *info;

    info = NULL;
    if (syscall_id < SYSCALLS_INFO_COUNT)
        info = SYSCALLS + syscall_id;

    return (info);
}
